config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "adverts#index"

  resources :adverts do
    resources :reviews, only: [:create]
    resources :bookings, only: [:new, :create]
    resources :favourites, only: [:create]
  end
  resources :profiles, path: 'users/profile'
  resources :reviews, only: [:destroy]
  resources :bookings, only: [ :destroy]
  resources :favourites, only: [:destroy]
end

app/views/shared/_advert_form.html.erb
<div class="container">
  <div class="d-flex justify-content-center newAdvertContainer">
    <div class="card cardFormRadius" style="width: 500px;">
      <div class="card-header">
        <% if current_page?(new_advert_path) %>
          <h2 class="text-center my-3">New Advert</h2>
        <% else %>
          <h2 class="text-center my-3">Edit Advert</h2>
        <% end %>
      </div>
      <div class="card-body">
        <%= simple_form_for @advert, html: { data: { controller: "character-count", character_min: 150, character_max: 1000}} do |f|%>
          <div class="group">
            <%= f.input :category_id, collection: Category.all, label_method: :name, value_method: :id, prompt: "-- Select a category --" %>
            <%= f.input :title, placeholder: "Gorgeous house in beachfront...", input_html: { class: 'form-control' } %>
          </div>
          <div class="group">
            <%= f.input :address, placeholder: "123 Georges st...", input_html: { class: 'form-control' } %>
            <%= f.input :city, placeholder: "Fort Lauderdale...", input_html: { class: 'form-control' } %>
          </div>
          <div class="group elt3">
            <%= f.input :state, label: "State/Region", placeholder: "Florida...", input_html: { class: 'form-control' } %>
            <%= f.input :postal_code, placeholder: "33301...", input_html: { class: 'form-control' } %>
            <%= f.input :country, as: :country, prompt: "-- Select a country --", input_html: { class: 'form-control' } %>
          </div>
          <hr>
          <div class="group elt3">
            <%= f.input :price, input_html: { class: 'form-control', min: 1 } %>
            <%= f.input :max_guests, input_html: { class: 'form-control', min: 1 } %>
            <%= f.input :min_nights, input_html: { class: 'form-control', min: 1 } %>
          </div>
          <div class="group elt3">
            <%= f.input :bedrooms, input_html: { class: 'form-control', min: 1 } %>
            <%= f.input :beds, input_html: { class: 'form-control', min: 1 } %>
            <%= f.input :bathrooms, input_html: { class: 'form-control', min: 1 } %>
          </div>
          <hr>
          <div class="form-group">
            <label>Amenities <span>*</span></label>
            <%= f.input :amenity_ids, as: :check_boxes, collection: Amenity.all, label_method: :name, value_method: :id, input_html: { class: 'form-control' }%>
          </div>
          <hr>
          <div class="group">
            <%= f.input :check_in, placeholder: "Gorgeous house in beachfront...", input_html: { class: 'form-control' } %>
            <%= f.input :check_out, placeholder: "Gorgeous house in beachfront...", input_html: { class: 'form-control' } %>
          </div>
          <hr>
          <div class="group">
            <%= f.input :smoking, as: :select, collection: [["Yes", true], ["No", false]], label: "Smoking allowed? *", prompt: "-- Select an option --", input_html: { class: 'form-control' } %>
            <%= f.input :party, as: :select, collection: [["Yes", true], ["No", false]], label: "Parties allowed? *", prompt: "-- Select an option --", input_html: { class: 'form-control' } %>
          </div>
          <hr>
          <div class="group elt1">
            <%= f.input :description, placeholder: "Gorgeous house in beachfront...", input_html: { class: 'form-control', data: { character_count_target: "input", action: "keyup->character-count#count"} } %>
          </div>
          <small data-character-count-target="message"></small>
          <hr>
          <div class="group elt1">
            <%= f.input :images, as: :file, input_html: { class: 'form-control', multiple: true, data: {image_preview_target: "input", action: 'change->image-preview#preview'} } %>
          </div>
          <div class="form-actions text-center mt-4 mb-2">
            <%= f.button :submit, class: "btn btn-success btn-lg" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="mt-auto <%= 'footerMobileMargin' if current_page?(root_path) || current_page?(adverts_path) || (@advert.present? && @advert.id.present? && current_page?(advert_path(@advert))) %>">
  <div class="container py-4">
    <div class="row align-items-center justify-content-between text-center text-md-start">
      <!-- Section Réseaux Sociaux -->
      <div class="col-md-4 text-md-end pe-0 order-1 order-md-2 mb-3 mb-md-0">
        <h5 class="text-uppercase">Follow Us</h5>
        <a href="#" class="text-dark me-3"><i class="fa-brands fa-facebook"></i></a>
        <a href="#" class="text-dark me-3"><i class="fa-brands fa-x-twitter"></i></a>
        <a href="#" class="text-dark"><i class="fab fa-instagram"></i></a>
      </div>

      <!-- Section Copyright -->
      <div class="col-md-4 my-auto order-2 order-md-1 copyright">
        <p class="mb-0">&copy; <%= Time.now.year %>   HeavenNest. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="<%= 'hide-header-mobile' if request.path.include?('/adverts/') || request.path.include?('/bookings/new') %>">
  <nav class="navbar py-3 ">
    <div class="container">
      <%= link_to root_path, class: "navbar-brand me-0" do %>
        <%= image_tag "logo.png", alt: "alttext", class: "logo" %>
      <% end %>
      <ul class="navbar-nav">
        <li class="nav-item d-none d-md-block">
          <%= form_with(url: adverts_path, method: :get, local: true, class: 'd-flex align-items-center position-relative me-3') do |f| %>
            <%= f.label :query, class: 'visually-hidden' %>
            <%= f.text_field :query, placeholder: "Search by city, state or country...", value: params[:query], class: "form-control", id: "inputSearch" %>
            <button type="submit" class="btn" id="iconSearch">
              <i class="fas fa-search"></i>
            </button>
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "New advert", new_advert_path, class: "btn btn-outline-success btn-lg me-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Profile", profile_path(current_user), class: "btn btn-outline-success btn-lg" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign-In", new_user_session_path, class: "btn btn-outline-success btn-lg" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <% if current_page?(root_path) || current_page?(adverts_path) %>
    <nav id="categoriesNav">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <%= form_with(url: adverts_path, method: :get, local: true, class: 'd-flex align-items-center justify-content-evenly') do %>
              <% Category.all.each do |category| %>
                <% active_class = params[:category].to_i == category.id ? 'active' : '' %>
                <button type="submit" name="category" value="<%= category.id %>" class="btn d-flex flex-column align-items-center justify-content-center categoriesButton <%= active_class %> ">
                  <% icon_class = case category.name
                    when 'Apartment' then 'building'
                    when 'House' then 'house'
                    when 'Room' then 'bed'
                    when 'Bungalow' then 'caravan'
                    when 'Chalet' then 'tree'
                    when 'Mansion' then 'house-chimney-crack'
                    when 'Unusual' then 'igloo'
                    when 'Villa' then 'house-flood-water'
                    when 'Studio' then 'city'
                    when 'Farm' then 'cow'
                    else 'question'
                  end %>
                  <i class="fa-solid fa-<%= icon_class %>"></i>
                  <span><%= category.name %></span>
                </button>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
  <% end %>
</header>

<%# Back button for mobile header  %>
<% if request.path.include?('/adverts/') || request.path.include?('/bookings/new') %>
  <header class="header-mobile">
    <%= link_to request.referer || root_path, class: "btn btn-outline-secondary p-0" do %>
      <div class="backButtonContainer d-flex align-items-center justify-content-center">
        <i class="fa-solid fa-arrow-left"></i>
      </div>
    <% end %>
  </header>
<% end %>

<%# Search input nav for mobile fixed bottom %>
<% if current_page?(root_path) || current_page?(adverts_path) %>
  <nav class="searchNavMobile d-md-none">
    <%= form_with(url: adverts_path, method: :get, local: true, class: 'd-flex align-items-center position-relative') do |f| %>
      <%= f.label :query, class: 'visually-hidden' %>
      <%= f.text_field :query, placeholder: "Search by city, state or country...", value: params[:query], class: "form-control", id: "inputSearch" %>
      <button type="submit" class="btn" id="iconSearch">
        <i class="fas fa-search"></i>
      </button>
    <% end %>
  </nav>
<% end %>

app/views/shared/_profile_adverts.html.erb
<% if @user == current_user %>
  <div class="d-flex justify-content-<%=@user.adverts.count <= 2 ? 'start' : 'between'%>" id="containerListingProfile">
    <% @user.adverts.each do |advert| %>
      <div class="col-12 col-md-6 col-lg-4 mb-0">
        <!-- Card component wrapped in link_to -->
          <div class="card shadow-sm mt-5 me-3 cardAdverts cardProfile position-relative" style="height: 400px;">
            <!-- Card Header with Poster URL -->
            <div class="card-header p-0" style="height: 50%; overflow: hidden;">
              <% if advert.images.present? %>
                <%= image_tag advert.images.first, alt: "alttext", style: "height: 100%; width:100%; object-fit: cover;" %>
              <% else %>
                <%= image_tag "test.jpg", alt: "alttext", style: "height: 100%; width:100%; object-fit: cover;" %>
              <% end %>
            </div>

            <!-- Card Body with Title, Rating, and Overview -->
            <div class="card-body position-relative" style="height: 35%; overflow: auto;">
              <h4 class="card-title m-0 mb-1"><strong><%= advert.title %></strong></h4>
              <p class="m-0"><em><%= advert.city %>, <%= advert.country %></em></p>
              <div class="d-flex flex-wrap align-items-center justify-content-evenly mt-4 detailsAdvert">
                <p class="mb-0"><i class="fa-solid fa-users me-3"></i><%= advert.max_guests %></p>
                <p class="mb-0"><i class="fa-solid fa-bed me-3"></i><%= advert.bedrooms %></p>
                <p class="mb-0"><i class="fa-solid fa-bath me-3"></i><%= advert.bathrooms %></p>
              </div>
            </div>

            <!-- Card Footer with Price -->
            <div class="card-footer d-flex justify-content-between align-items-center" style="height: 15%;">
              <p class="mb-0" id="priceAdvert">€ <%= advert.price %> / night</p>
              <div>
                <%= link_to advert_path(advert), class: "btn btn-outline-success", id:"editButton" do %>
                  <i class="fa-solid fa-eye"></i>
                <% end %>
                <%= link_to edit_advert_path(advert), class: "btn btn-outline-success", id:"editButton" do %>
                  <i class="fa-solid fa-pencil"></i>
                <% end %>
                <%= button_to advert_path(advert), method: :delete, form_class: 'delete-alertbox', class: "btn btn-outline-danger", id:"editButton" do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
              </div>
            </div>
          </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="d-flex justify-content-<%=@user.adverts.count <= 2 ? 'start' : 'between'%>" id="containerListingProfile">
    <% @user.adverts.each do |advert| %>
      <div class="col-12 col-md-6 col-lg-4 mb-0">
        <!-- Card component wrapped in link_to -->
        <%= link_to advert_path(advert), class: "text-decoration-none" do %>
          <div class="card shadow-sm mt-5 me-3 cardAdverts cardProfile position-relative" style="height: 400px;">
            <!-- Card Header with Poster URL -->
            <div class="card-header p-0" style="height: 50%; overflow: hidden;">
              <% if advert.images.present? %>
                <%= image_tag advert.images.first, alt: "alttext", style: "height: 100%; width:100%; object-fit: cover;" %>
              <% else %>
                <%= image_tag "test.jpg", alt: "alttext", style: "height: 100%; width:100%; object-fit: cover;" %>
              <% end %>
            </div>

            <!-- Card Body with Title, Rating, and Overview -->
            <div class="card-body position-relative" style="height: 35%; overflow: auto;">
              <h4 class="card-title m-0 mb-1"><strong><%= advert.title %></strong></h4>
              <p class="m-0"><em><%= advert.city %>, <%= advert.country %></em></p>
              <div class="d-flex flex-wrap align-items-center justify-content-evenly mt-4 detailsAdvert">
                <p class="mb-0"><i class="fa-solid fa-users me-3"></i><%= advert.max_guests %></p>
                <p class="mb-0"><i class="fa-solid fa-bed me-3"></i><%= advert.bedrooms %></p>
                <p class="mb-0"><i class="fa-solid fa-bath me-3"></i><%= advert.bathrooms %></p>
              </div>
            </div>

            <!-- Card Footer with Price -->
            <div class="card-footer d-flex justify-content-between align-items-center" style="height: 15%;">
              <p class="mb-0" id="priceAdvert">€ <%= advert.price %> / night</p>
              <div class="d-flex align-items-center">
              <% if advert.user.profile_picture.present? %>
                <%= image_tag advert.user.profile_picture, alt: "Profile Picture" %>
              <% else %>
                <%= image_tag "logo.png", alt: "Profile Picture" %>
              <% end %>
              <p class="mb-0 ms-1" id="hostName"><%= advert.user.first_name %></p>
            </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_profile_user_connected.html.erb
<hr class="my-5">
<h2 class="borderHeadersProfile"><%= @user.first_name %>'s bookings (<%= @user.bookings.count %>)</h2>
<% if @user.bookings.blank? %>
  <p class="text-center mt-4"><strong><%= @user.first_name %> has not made any bookings yet.</strong></p>
<% else %>
  <div class="d-flex justify-content-<%=@user.adverts.count <= 2 ? 'start' : 'between'%>" id="containerListingProfile">
    <% @user.bookings.each do |booking| %>
      <div class="col-12 col-md-6 col-lg-4 mb-0">
        <!-- Card component wrapped in link_to -->
        <div class="card shadow-sm mt-5 me-3 cardAdverts cardProfile position-relative" style="height: 400px;">
          <!-- Card Header with Poster URL -->
          <div class="card-header p-0" style="height: 50%; overflow: hidden;">
            <% if booking.advert.images.present? %>
              <%= image_tag booking.advert.images.first, alt: "alttext", style: "height: 100%; width:100%; object-fit: cover;" %>
            <% else %>
              <%= image_tag "test.jpg", alt: "alttext", style: "height: 100%; width:100%; object-fit: cover;" %>
            <% end %>
          </div>

          <!-- Card Body with Title, Rating, and Overview -->
          <div class="card-body position-relative" style="height: 35%; overflow: auto;">
            <h4 class="card-title m-0 mb-1"><strong><%= booking.start_date.strftime("%d/%m/%y") %> - <%= booking.end_date.strftime("%d/%m/%y") %></strong></h4>
            <p class="m-0"><em><%= booking.advert.city %>, <%= booking.advert.country %></em></p>
            <div class="d-flex flex-wrap align-items-center justify-content-evenly mt-4 detailsAdvert">
              <p class="mb-0"><i class="fa-solid fa-users me-3"></i><%= booking.advert.max_guests %></p>
              <p class="mb-0"><i class="fa-solid fa-bed me-3"></i><%= booking.advert.bedrooms %></p>
              <p class="mb-0"><i class="fa-solid fa-bath me-3"></i><%= booking.advert.bathrooms %></p>
            </div>
          </div>

          <!-- Card Footer with Price -->
          <div class="card-footer d-flex justify-content-between align-items-center" style="height: 15%;">
            <p class="mb-0" id="priceAdvert">€ <%= number_with_precision(booking.total_price, precision: (booking.total_price % 1 == 0 ? 0 : 2)) %> / <%= pluralize(booking.nights_count, "night")%></p>
            <div>
              <%= link_to advert_path(booking.advert), class: "btn btn-outline-success", id:"editButton" do %>
                <i class="fa-solid fa-eye"></i>
              <% end %>

              <% if booking.start_date > Date.today %>
                <%= button_to booking_path(booking), method: :delete, form_class: 'delete-alertbox', class: "btn btn-outline-danger", id:"editButton" do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
              <% elsif booking.start_date <= Date.today && booking.end_date >= Date.today %>
                <div class="btn btn-outline-secondary" data-bs-toggle="tooltip" title="Your stay has started, enjoy! (<%= booking.start_date.strftime("%d/%m/%y") %> - <%= booking.end_date.strftime("%d/%m/%y") %>)">
                  <i class="fa-solid fa-spinner spin"></i>
                </div>
              <% else %>
                <%= link_to "#{advert_path(booking.advert)}#review-form", class: "text-decoration-none btn btn-outline-secondary", data: {bs_toggle: "tooltip"}, title: "Write a comment!" do %>
                  <i class="fa-solid fa-comment-medical"></i>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<% if @user.favourites.present? %>
  <hr class="my-5">
  <h2 class="borderHeadersProfile"><%= @user.first_name %>'s favourites (<%= @user.favourites.count %>)</h2>
  <div class="d-flex justify-content-<%=@user.favourites.count <= 2 ? 'start' : 'between'%>" id="containerListingProfile">
    <% @user.favourites.each do |favourite| %>
      <div class="col-12 col-md-6 col-lg-4 mb-0">
        <!-- Card component wrapped in link_to -->
        <%= link_to advert_path(favourite.advert), class: "text-decoration-none" do %>
          <div class="card shadow-sm mt-5 me-3 cardAdverts cardProfile position-relative" style="height: 400px;">
            <!-- Card Header with Poster URL -->
            <div class="card-header p-0" style="height: 50%; overflow: hidden;">
              <% if favourite.advert.images.present? %>
                <%= image_tag favourite.advert.images.first, alt: "alttext", style: "height: 100%; width:100%; object-fit: cover;" %>
              <% else %>
                <%= image_tag "test.jpg", alt: "alttext", style: "height: 100%; width:100%; object-fit: cover;" %>
              <% end %>
            </div>

            <!-- Card Body with Title, Rating, and Overview -->
            <div class="card-body position-relative" style="height: 35%; overflow: auto;">
              <h4 class="card-title m-0 mb-1"><strong><%= favourite.advert.title %></strong></h4>
              <p class="m-0"><em><%= favourite.advert.city %>, <%= favourite.advert.country %></em></p>
              <div class="d-flex flex-wrap align-items-center justify-content-evenly mt-4 detailsAdvert">
                <p class="mb-0"><i class="fa-solid fa-users me-3"></i><%= favourite.advert.max_guests %></p>
                <p class="mb-0"><i class="fa-solid fa-bed me-3"></i><%= favourite.advert.bedrooms %></p>
                <p class="mb-0"><i class="fa-solid fa-bath me-3"></i><%= favourite.advert.bathrooms %></p>
              </div>
            </div>

            <!-- Card Footer with Price -->
            <div class="card-footer d-flex justify-content-between align-items-center" style="height: 15%;">
              <p class="mb-0" id="priceAdvert">€ <%= favourite.advert.price %> / night</p>
              <div class="d-flex align-items-center position-relative" data-controller ="favourite">
                  <% if current_user.favourited?(favourite.advert) %>
                    <% favourite = current_user.favourites.find_by(advert_id: favourite.advert.id) %>
                    <%= button_to favourite_path(favourite), method: :delete, class: "btn favButton", data: { action: 'click->favourite#stopPropagation' }  do %>
                      <i class="fa-solid fa-heart"></i>
                    <% end %>
                  <% else %>
                    <%= button_to advert_favourites_path(advert), method: :post, class: "btn favButton", data: { action: 'click->favourite#stopPropagation' } do %>
                      <i class="fa-regular fa-heart"></i>
                    <% end %>
                  <% end %>
                <div class="d-flex align-items-center">
                  <% if favourite.advert.user.profile_picture.present? %>
                    <%= image_tag favourite.advert.user.profile_picture, alt: "Profile Picture" %>
                  <% else %>
                    <%= image_tag "logo.png", alt: "Profile Picture" %>
                  <% end %>
                  <p class="mb-0 ms-1" id="hostName"><%= favourite.advert.user.first_name %></p>
                </div>
            </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>