config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "adverts#index"

  resources :adverts do
    resources :reviews, only: [:create]
    resources :bookings, only: [:new, :create]
    resources :favourites, only: [:create]
  end
  resources :profiles, path: 'users/profile'
  resources :reviews, only: [:destroy]
  resources :bookings, only: [ :destroy]
  resources :favourites, only: [:destroy]
end

app/models/advert.rb
class Advert < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :favourites
  has_many :reviews
  has_many :advert_amenities, dependent: :destroy
  has_many :amenities, through: :advert_amenities
  has_many :bookings # Association pour les réservations liées à l'annonce
  has_many :reservations, through: :bookings, source: :user # Utilisateurs ayant réservé cette annonce
  has_many_attached :images

  validates :title, presence: true, length: { maximum: 70}
  validates :description, presence: true, length: { minimum: 150, maximum: 1000}
  validates :price, :max_guests, :min_nights, :bedrooms, :beds, :bathrooms, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :check_in, :check_out, :address, :city, :state, :postal_code, :country, :category_id, presence: true
  validates :images, presence: true
  validates :smoking, :party, inclusion: { in: [true, false], message: "must be selected"}
  validate :validate_amenities_count
  validate :at_least_three_image
  validate :validate_images_count

  private

  def validate_amenities_count
    if amenity_ids.size < 2
      errors.add(:amenity_ids, "must select at least 2 amenities")
    end
  end

  def at_least_three_image
    if images.blank? || images.size < 3
      errors.add(:images, "must have at least three images")
    end
  end

  def validate_images_count
    if images.size > 10
      errors.add(:images, "You can upload a maximum of 10 images")
    end
  end
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index

    if params[:query].present?
      query = params[:query]
      @adverts = Advert.where("city ILIKE :query OR state ILIKE :query OR country ILIKE :query", query: "%#{query}%")

    elsif params[:category].present?
      @adverts = Advert.where(category_id: params[:category])

    else
      @adverts = Advert.all
    end
  end

  def new
    @user = current_user
    @advert = Advert.new(user_id: @user.id)
  end

  def create
    @user = current_user
    @advert = @user.adverts.build(advert_params)
    if @advert.save
      redirect_to advert_path(@advert), notice: "Advert successfully created", status: :see_other
    else
      render :new, status: :unprocessable_entity
    end

  end

  def show
    @advert = Advert.find(params[:id])
    @review = Review.new(advert_id: @advert)
    @reviews = @advert.reviews
    if @reviews.any?
      @average_rating = @reviews.average(:rating).to_f
    else
      @average_rating = nil
    end
  end

  def edit
    @advert = Advert.find(params[:id])
  end

  def update
    @advert = Advert.find(params[:id])

    #Keep the existing images et add the new ones if exists
    if params[:advert][:images].present?
      @advert.images.attach(params[:advert][:images]) #Add new images
    end

    #Delete all the images in the params hash to avoid the reboot  of it
    params[:advert].delete(:images)
    if @advert.update(advert_params)
      redirect_to advert_path(@advert), notice: "Advert successfully updated", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @advert = Advert.find(params[:id])
    @advert.destroy
    redirect_to root_path, notice: "Advert successfully deleted", status: :see_other
  end

  private

  def advert_params
    params.require(:advert).permit(:title, :description, :price, :max_guests, :min_nights, :bedrooms, :beds, :bathrooms, :check_in, :check_out, :smoking, :party, :address, :city, :state, :postal_code, :country, :category_id, amenity_ids: [], images: [])
  end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/views/adverts/edit.html.erb
<%= render "shared/advert_form", advert: @advert %>

app/views/adverts/index.html.erb
<div class="container">
  <div class="row">
    <% if @adverts.blank? %>
      <h1 class="text-center mt-5 my-4">There are no adverts yet</h1>
    <% else %>
      <% @adverts.each do |advert| %>
        <div class="col-12 col-md-6 col-lg-4 mb-0">
          <!-- Card component wrapped in link_to -->
          <%= link_to advert_path(advert), class: "text-decoration-none anchor-card" do %>
            <div class="card shadow-sm mt-5 cardAdverts" style="height: 400px;">
              <!-- Card Header with Poster URL -->
              <div class="card-header p-0" style="height: 50%; overflow: hidden;">

                <% if advert.images.present? %>
                  <%= image_tag advert.images.first, alt: "alttext", style: "height: 100%; width:100%; object-fit: cover;" %>
                <% else %>
                  <%= image_tag "test.jpg", alt: "alttext", style: "height: 100%; width:100%; object-fit: cover;" %>
                <% end %>
              </div>

              <!-- Card Body with Title, Rating, and Overview -->
              <div class="card-body position-relative" style="height: 35%; overflow: auto;">
                <h4 class="card-title m-0 mb-1"><strong><%= advert.title %></strong></h4>
                <p class="m-0"><em><%= advert.city %>, <%= advert.country %></em></p>
                <div class="d-flex flex-wrap align-items-center justify-content-evenly mt-4 detailsAdvert">
                  <p class="mb-0"><i class="fa-solid fa-users me-3"></i><%= advert.max_guests %></p>
                  <p class="mb-0"><i class="fa-solid fa-bed me-3"></i><%= advert.bedrooms %></p>
                  <p class="mb-0"><i class="fa-solid fa-bath me-3"></i><%= advert.bathrooms %></p>
                </div>
              </div>

              <!-- Card Footer with Price -->
              <div class="card-footer d-flex justify-content-between align-items-center" style="height: 15%;">
                <p class="mb-0" id="priceAdvert">€ <%= advert.price %> / night</p>
                <div class="d-flex align-items-center position-relative" data-controller ="favourite">
                  <% if user_signed_in? && current_user != advert.user %>
                    <% if current_user.favourited?(advert) %>
                      <% favourite = current_user.favourites.find_by(advert_id: advert.id) %>
                      <%= button_to favourite_path(favourite), method: :delete, class: "btn favButton", data: { action: 'click->favourite#stopPropagation' }  do %>
                        <i class="fa-solid fa-heart"></i>
                      <% end %>
                    <% else %>
                      <%= button_to advert_favourites_path(advert), method: :post, class: "btn favButton", data: { action: 'click->favourite#stopPropagation' } do %>
                        <i class="fa-regular fa-heart"></i>
                      <% end %>
                    <% end %>
                  <% end %>
                  <div class="d-flex align-items-center">
                    <% if advert.user.profile_picture.present? %>
                      <%= image_tag advert.user.profile_picture, alt: "Profile Picture" %>
                    <% else %>
                      <%= image_tag "logo.png", alt: "Profile Picture" %>
                    <% end %>
                    <p class="mb-0 ms-1" id="hostName"><%= advert.user.first_name %></p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/adverts/new.html.erb
<%= render "shared/advert_form", advert: @advert %>

app/views/adverts/show.html.erb
<div class="container advertShow">
  <div class="row carouselContainer position-relative">
    <% if user_signed_in? && current_user != @advert.user %>
      <% if current_user.favourited?(@advert) %>
        <% favourite = current_user.favourites.find_by(advert_id: @advert.id) %>
        <%= button_to favourite_path(favourite), method: :delete, class: "btn favButton showFavButton", data: { action: 'click->favourite#stopPropagation' }  do %>
          <div class="favButtonContainer d-flex align-items-center justify-content-center">
            <i class="fa-solid fa-heart"></i>
          </div>
        <% end %>
      <% else %>
        <%= button_to advert_favourites_path(@advert), method: :post, class: "btn favButton showFavButton", data: { action: 'click->favourite#stopPropagation' } do %>
          <div class="favButtonContainer d-flex align-items-center justify-content-center">
            <i class="fa-regular fa-heart"></i>
          </div>
        <% end %>
      <% end %>
    <% end %>
    <!-- Colonne gauche : Carousel -->
    <div class="col-lg-8 p-0">
      <div id="advertCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <% @advert.images.each_with_index do |image, index| %>
            <div class="carousel-item <%= 'active' if index == 0 %>">
              <%= image_tag image, class: "d-block w-100", id:"carouselImage" %> <!-- Carousel image -->
            </div>
          <% end %>
        </div>
        <!-- Contrôles de navigation -->
        <button class="carousel-control-prev" type="button" data-bs-target="#advertCarousel" data-bs-slide="prev">
          <div class="d-flex align-items-center justify-content-center controlIconContainer">
            <i class="fa-solid fa-angle-left"></i>
            <span class="visually-hidden">Previous</span>
          </div>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#advertCarousel" data-bs-slide="next">
          <div class="d-flex align-items-center justify-content-center controlIconContainer">
            <i class="fa-solid fa-angle-right"></i>
            <span class="visually-hidden">Next</span>
          </div>
        </button>
      </div>
    </div>

    <!-- Colonne droite : Images miniatures sur grands écrans -->
    <div class="col-lg-4 d-none d-lg-block p-0 smallImagesContainer">
      <div class="d-flex flex-wrap h-100">
        <% @advert.images.each_with_index do |image, index| %>
          <div class="flex-fill" style="width: 50%;">
            <%= image_tag image, class: "img-thumbnail p-0 border-0 rounded-0 w-100 h-100", style: "object-fit: cover;", data: {bs_target: "#advertCarousel", bs_slide_to: index} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Miniatures en dessous pour les écrans mobiles et tablettes -->
  <div class="row d-lg-none">
    <div class="col-12 smallImagesScroll p-0">
      <div class="d-flex flex-row overflow-auto">
        <% @advert.images.each_with_index do |image, index| %>
          <div class="flex-shrink-0" style="width: 120px;">
            <%= image_tag image, class: "img-thumbnail border-0 rounded-0 p-0", style: "width: 100%; height: 100px; object-fit: cover;", data: {bs_target: "#advertCarousel", bs_slide_to: index} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <!-- Colonne pour les détails de l'annonce -->
    <div class="col-md-8">
      <article class="detailsAdvert mt-5">
        <div>
          <h1><%= @advert.title %></h1>
          <h3><%= @advert.city %>, <%= @advert.state %>, <%= @advert.country %></h3>
          <p class="m-0">Up to <%= pluralize(@advert.max_guests, 'traveller') %> | <%= pluralize(@advert.bedrooms, 'bedroom') %> | <%= pluralize(@advert.beds, 'bed') %> | <%= pluralize(@advert.bathrooms, 'bathroom') %> </p>
          <p class="m-0">Category: <%= @advert.category.name %></p>
          <div class="d-flex">
            <p class="m-0"><%= pluralize(@advert.reviews.count, 'review') %></p>
            <p class="m-0">

            <% if @advert.reviews.any? && @average_rating.present? %>
              <% if @average_rating > 0 %>
                <span class="ms-2"> |
                  <% @average_rating.to_i.times do %>
                    <i class="fas fa-star star-yellow"></i>
                  <% end %>
                  <span class="text-muted">(Avg. <%= @average_rating.round(1) %> stars)</span>
                </span>
              <% end %>
            <% end %>
          </p>
          </div>
        </div>
        <hr>
        <div class="d-flex align-items-center hostDetails">
          <%= link_to profile_path(@advert.user), target: "_blank" do %>
            <%= image_tag @advert.user.profile_picture.present? ? @advert.user.profile_picture : "logo.png" %>
          <% end %>
          <div class="ms-4 hostDetailsContact">
            <p class="m-0">Host: <%= @advert.user.first_name %> <%= @advert.user.last_name %></p>
            <% if @advert.user.city.present? && @advert.user.country.present?  %>
              <p class="m-0" id="hostAddress">Lives in <%= @advert.user.city %>, <%= @advert.user.country %></p>
            <% end %>
          </div>
        </div>
        <hr>
        <div>
          <h2 class="borderHeadersProfile">About the place</h2>
          <div class="advertDescription">
            <%= simple_format(@advert.description) %>
          </div>
        </div>
        <hr>
        <div>
          <h2 class="borderHeadersProfile">What this place offers (<%= @advert.amenities.count %>)</h2>
          <div class="advertAmenities">
            <ul class="d-flex flex-wrap justify-content-between p-0 list-unstyled">
              <% @advert.amenities.each do |amenity| %>
                <li><%= amenity.name %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <hr>
        <div>
          <h2 class="borderHeadersProfile">Things to know</h2>
          <div class="advertRules">
            <div class="d-flex flex-wrap justify-content-between">
              <p class="m-0 mb-2">Check-in: <%= @advert.check_in.strftime("%H:%M") %></p>
              <p class="m-0 mb-2">Check-out: <%= @advert.check_out.strftime("%H:%M") %></p>
              <p class="m-0">Smoking: <%= @advert.smoking == true ? "Yes" : "No"%> </p>
              <p class="m-0">Party: <%= @advert.party == true ? "Yes" : "No" %> </p>
            </div>
          </div>
        </div>
        <hr>
      </article>
    </div>
     <!-- Colonne pour le prix, nombre de nuits, et le bouton Réserver -->
    <div class="col-md-4 pe-0">
      <div class="sticky-top d-md-block d-none mt-5 z-0 detailsPrice" style="top: 100px;">
        <div class="card shadow-sm p-5">
          <h3 class="">€ <%= @advert.price %> / night</h3>

          <% if current_user == @advert.user %>
            <%= link_to "Edit", edit_advert_path(@advert), class: "btn btn-success btn-lg mt-3 p-3" %>
          <% else %>
            <%= link_to "Reserve", new_advert_booking_path(@advert), class: "btn btn-success btn-lg mt-3 p-3" %>
          <% end %>
        </div>
      </div>
    </div>
    <!-- Bloc sticky pour mobile (visible sur sm et inférieurs) -->
    <div class="d-md-none p-0">
      <div class="col-12">
        <div class="sticky-bottom text-center">
          <div class="d-flex align-items-center justify-content-between containerBooking">
            <h3 class="mb-0">€ <%= @advert.price %> / night</h3>
            <%= link_to "Reserve", new_advert_booking_path(@advert), class: "btn btn-success btn-lg btn-block" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <article class="bottomAdvert">
      <div>
        <h2 class="borderHeadersProfile">Where you'll be</h2>
        <div class="map">
          <p class="mb-0 mt-2"><%= @advert.city %>, <%= @advert.state %>, <%= @advert.country %></p>
          <div>
            <%= image_tag "map.png" %>
          </div>
        </div>
      </div>
      <hr>
      <div>
        <h2 class="borderHeadersProfile">What travellers say</h2>
        <div class="row d-flex justify-content-end mt-4">
          <div class="col-md-6">
            <% if @advert.reviews.blank? %>
                <h4 class="mt-5 text-center">Be the first to review this place!</h4>
            <% else %>
              <div class="review-container mt-2" style="max-height: 200px; overflow-y: auto;">
                <% @advert.reviews.each do |review| %>
                  <% if review.valid? %>
                    <div class="mt-0 pt-2 position-relative review-item">
                      <% review.rating.times do %>
                        <i class="fas fa-star star-yellow"></i>
                      <% end %>
                      <small>
                        <em class="text-muted">
                        <%= distance_of_time_in_words_to_now(review.created_at) %> ago
                        </em>
                      </small>
                      <p class="pe-4 mb-0 mt-1"><%= review.content %></p>
                      <p><small>by <%= review.user.first_name %> <%= review.user.last_name  %>
                        <%= link_to profile_path(review.user), target: "_blank" do %>
                          <%= image_tag(review.user.profile_picture.present? ? review.user.profile_picture : "logo.png", alt: "Profile Picture", class: "reviewsPicture") %>
                        <% end %>
                      </small></p>
                      <% if review.user == current_user %>
                        <%= button_to review_path(review), method: :delete, form_class: 'delete-alertbox', class: "btn  text-danger", id: "deleteButton" do %>
                        <i class="fa-solid fa-trash"></i>
                        <% end %>
                      <% end %>
                      <hr class="mb-0">
                    </div>
                  <% else %>
                    <h4 class="mt-5 text-center">Be the first to add a review!</h4>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          </div>
          <div class="col-md-6" id="review-form">
            <article class="card shadow-sm mt-3 mb-5">
              <div class="card-body">
                <h4 class="text-center mb-4">Add a Review</h4>
                <%= simple_form_for [@advert, @review] do |f| %>
                  <%= f.input :content, placeholder: 'Add your comment...', label: false, input_html: { class: 'form-control mt-3' } %>
                  <%= f.input :rating, as: :select, collection: 1..5, prompt: 'Rate the list (max:5)', label: false, input_html: { class: 'form-control mt-3' } %>
                  <%= f.submit "Add Review", class: 'btn btn-outline-success btn-block mt-3' %>
                <% end %>
              </div>
            </article>
          </div>
        </div>
      </div>
    </article>
  </div>
  </div>
</div>